export const baseURL = 'http://192.168.0.192:3000/';

export const SIGNUP_TOKEN = 'SIGNUP_TOKEN';
export const SIGNUP_CLUSTER_ID = 'SIGNUP_CLUSTER_ID';
export const SIGNUP_EPISODE_ID = 'SIGNUP_EPISODE_ID';
export const SIGNUP_USER_ID = 'SIGNUP_USER_ID';

export const SIGNUP_USER_REQUEST = 'SIGNUP_USER_REQUEST';
export const SIGNUP_USER_SUCCESS = 'SIGNUP_USER_SUCCESS';
export const SIGNUP_USER_ERROR = 'SIGNUP_USER_ERROR';

export const CATEGORIES_USER_REQUEST = 'CATEGORIES_USER_REQUEST';
export const CATEGORIES_USER_SUCCESS = 'CATEGORIES_USER_SUCCESS';
export const CATEGORIES_USER_ERROR = 'CATEGORIES_USER_ERROR';
