export const baseURL = 'http://192.168.0.192:3000/';

export const AUTH_TOKEN = 'AUTH_TOKEN';

export const SIGNUP_TOKEN = 'SIGNUP_TOKEN';
export const SIGNUP_CLUSTER_ID = 'SIGNUP_CLUSTER_ID';
export const SIGNUP_EPISODE_ID = 'SIGNUP_EPISODE_ID';
export const SIGNUP_USER_ID = 'SIGNUP_USER_ID';

export const USER_DETAIL_REQUEST = 'USER_DETAIL_REQUEST';
export const USER_DETAIL_SUCCESS = 'USER_DETAIL_SUCCESS';
export const USER_DETAIL_ERROR = 'USER_DETAIL_ERROR';

export const UPDATE_USER_DETAIL_REQUEST = 'UPDATE_USER_DETAIL_REQUEST';
export const UPDATE_USER_DETAIL_SUCCESS = 'UPDATE_USER_DETAIL_SUCCESS';
export const UPDATE_USER_DETAIL_ERROR = 'UPDATE_USER_DETAIL_ERROR';

export const SIGNUP_USER_REQUEST = 'SIGNUP_USER_REQUEST';
export const SIGNUP_USER_SUCCESS = 'SIGNUP_USER_SUCCESS';
export const SIGNUP_USER_ERROR = 'SIGNUP_USER_ERROR';

export const CATEGORIES_USER_REQUEST = 'CATEGORIES_USER_REQUEST';
export const CATEGORIES_USER_SUCCESS = 'CATEGORIES_USER_SUCCESS';
export const CATEGORIES_USER_ERROR = 'CATEGORIES_USER_ERROR';

export const USER_ADDRESS_REQUEST = 'USER_ADDRESS_REQUEST';
export const USER_ADDRESS_SUCCESS = 'USER_ADDRESS_SUCCESS';
export const USER_ADDRESS_ERROR = 'USER_ADDRESS_ERROR';
