export const images = {
  welcomeBackIMG: require('../assets/images/background.png'),
  facebook: require('../assets/images/Facebook/facebook.png'),
  google: require('../assets/images/Google/google.png'),
  commonBackGround: require('../assets/images/Sign-Up.png'),
  showPass: require('../assets/images/ShowImg/Show.png'),
  hidePass: require('../assets/images/hidden.png'),
  BackImg: require('../assets/images/BackImg/Path.png'),
  Menu: require('../assets/images/Menu/Menu.png'),
  Location: require('../assets/images/Location/Location.png'),
  Helps: require('../assets/images/Helps/Vector.png'),
  Message: require('../assets/images/Message/Message.png'),
  MyProfile: require('../assets/images/Profile/Profile.png'),
  Setting: require('../assets/images/Setting/Setting.png'),
  Payment: require('../assets/images/Wallet/Wallet.png'),
  MyOrder: require('../assets/images/Document/Document.png'),
  ProfileBackGround: require('../assets/images/ProfileBackground/Profile.png'),
};
