export const images = {
  welcomeBackIMG: require('../assets/images/background.png'),
  facebook: require('../assets/images/Facebook/facebook.png'),
  google: require('../assets/images/Google/google.png'),
  commonBackGround: require('../assets/images/Sign-Up.png'),
  showPass: require('../assets/images/ShowImg/Show.png'),
  hidePass: require('../assets/images/hidden.png'),
  BackImg: require('../assets/images/BackImg/Path.png'),
  Menu: require('../assets/images/Menu/Menu.png'),
  Location: require('../assets/images/Location/Location.png'),
  Helps: require('../assets/images/Helps/Vector.png'),
  Message: require('../assets/images/Message/Message.png'),
  MyProfile: require('../assets/images/Profile/Profile.png'),
  Setting: require('../assets/images/Setting/Setting.png'),
  Payment: require('../assets/images/Wallet/Wallet.png'),
  MyOrder: require('../assets/images/Document/Document.png'),
  ProfileBackGround: require('../assets/images/ProfileBackground/Profile.png'),
  ProfileImage: require('../assets/images/ProfileImg/Profileimage.png'),
  HeaderAero: require('../assets/images/HeaderAero/aero.png'),
  search: require('../assets/images/search/search.png'),
  filter: require('../assets/images/filter/filter.png'),
  Burger: require('../assets/images/burger/Burger.png'),
  Donat: require('../assets/images/Donat/donat.png'),
  Pizza: require('../assets/images/Pizza/pizza.png'),
  Mexican: require('../assets/images/Mexican/mexican.png'),
  Asian: require('../assets/images/Asian/asian.png'),
  Swits: require('../assets/images/Swits/swits.png'),
};
